definitions:
  auth.GUIDTokens:
    description: структура для получения токена.
    properties:
      GUID:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/get-tokens:
    post:
      consumes:
      - application/json
      parameters:
      - description: GUID пользователя
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.GUIDTokens'
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: bad request
          schema:
            additionalProperties: true
            type: object
      summary: Эндпойт для получения пары токенов
      tags:
      - Auth
swagger: "2.0"
